# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeculativeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/specdecode.SpeculativeService/Generate',
                request_serializer=inference__pb2.GenerateRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.VerifyDraftToken = channel.unary_unary(
                '/specdecode.SpeculativeService/VerifyDraftToken',
                request_serializer=inference__pb2.VerifyRequest.SerializeToString,
                response_deserializer=inference__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.VerifyDraftChunk = channel.unary_unary(
                '/specdecode.SpeculativeService/VerifyDraftChunk',
                request_serializer=inference__pb2.VerifyChunkRequest.SerializeToString,
                response_deserializer=inference__pb2.VerifyChunkResponse.FromString,
                _registered_method=True)


class SpeculativeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Existing single-token generation, if used
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDraftToken(self, request, context):
        """Possibly existing single-token verification, if you keep it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDraftChunk(self, request, context):
        """NEW: single-shot chunk verification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeculativeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=inference__pb2.GenerateRequest.FromString,
                    response_serializer=inference__pb2.GenerateResponse.SerializeToString,
            ),
            'VerifyDraftToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDraftToken,
                    request_deserializer=inference__pb2.VerifyRequest.FromString,
                    response_serializer=inference__pb2.VerifyResponse.SerializeToString,
            ),
            'VerifyDraftChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDraftChunk,
                    request_deserializer=inference__pb2.VerifyChunkRequest.FromString,
                    response_serializer=inference__pb2.VerifyChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'specdecode.SpeculativeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('specdecode.SpeculativeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeculativeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specdecode.SpeculativeService/Generate',
            inference__pb2.GenerateRequest.SerializeToString,
            inference__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDraftToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specdecode.SpeculativeService/VerifyDraftToken',
            inference__pb2.VerifyRequest.SerializeToString,
            inference__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDraftChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/specdecode.SpeculativeService/VerifyDraftChunk',
            inference__pb2.VerifyChunkRequest.SerializeToString,
            inference__pb2.VerifyChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
